[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "plantbrain-Signalize"
version = "0.1.0"
description = "A signal processing and anomaly detection package by plantBrain with FFT, Kalman Filter, and Wavelet Transform support."
authors = ["Himanshu Ranjan <Himanshu.ranjan@algo8.ai>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ALGO8AI/plantbrain-Signalize.git"
homepage = "https://github.com/ALGO8AI/plantbrain-Signalize.git"

[tool.poetry.dependencies]
python = ">=3.11.0"
scikit-learn = ">=1.6.1"
pandas = ">=2.2.3"
numpy = ">=2.1.3"
scipy = ">=1.9.0"
pykalman = ">=0.9.5"
pywt = ">=1.2.0"
matplotlib = ">=3.10.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[tool.poetry.urls]
"Documentation" = "https://github.com/ALGO8AI/plantbrain-Signalize.git"
"Source" = "https://github.com/ALGO8AI/plantbrain-Signalize.git"

[tool.poetry.classifiers]
"Programming Language :: Python :: 3"
"License :: OSI Approved :: MIT License"
"Operating System :: OS Independent"
"Intended Audience :: Developers"
"Topic :: Scientific/Engineering :: Artificial Intelligence"
"Topic :: Software Development :: Libraries :: Python Modules"

[tool.poetry.scripts]
# If you plan to add command-line tools in the future
# "plantbrain_signalize" = "plantbrain_signalize.cli:main"
